### Model within a limited range of errors: maximum coverage

Read individual data and convert

- Geographic level: tract
- Attributes: VOTINGAGE (2) $*$ HISPANIC (2) $*$ CENRACE (63)

In [1]:
import pandas as pd
import numpy as np

filename_hist = 'data/franklin_hist.csv'
hist = pd.read_csv(filename_hist)

# block to tract
hist['TRACT'] = hist['GEOID10'].astype(str).str[:11]
col_names = hist.columns.to_numpy()
col_names = np.delete(col_names, [0, -1])
hist = hist.groupby('TRACT').sum()[col_names]
hist = hist.reset_index()
hist

,TRACT,00000000,00000001,00000002,00000003,00000004,00000005,00000006,00000007,00000008,...,07010153,07010154,07010155,07010156,07010157,07010158,07010159,07010160,07010161,07010162
0,39049000110,438,6,0,7,0,4,5,1,0,...,0,0,0,0,0,0,0,0,0,0
1,39049000120,467,4,0,11,0,2,2,0,2,...,0,0,0,0,0,0,0,0,0,0
2,39049000210,430,11,0,6,0,4,4,1,4,...,0,0,0,0,0,0,0,0,0,0
3,39049000220,653,3,1,12,0,6,7,0,6,...,0,0,0,0,0,0,0,0,0,0
4,39049000310,313,205,0,17,0,2,19,0,4,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,39049010500,1821,35,1,409,0,2,5,2,22,...,0,0,0,0,0,0,0,0,0,0
280,39049010601,1408,36,0,146,0,3,12,0,15,...,0,0,0,0,0,0,0,0,0,0
281,39049010602,1585,45,3,139,0,4,7,2,9,...,0,0,0,0,0,0,0,0,0,0
282,39049010700,83,11,0,4,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
283,39049980000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
# HHGQ (8) $*$ VOTINGAGE (2) $*$ HISPANIC (2) $*$ CENRACE (63) to VOTINGAGE (2) $*$ HISPANIC (2) $*$ RACE (7)
n2, n3, n4 = 2, 2, 63

for y in range(n2):  # voting age
    y = '{number:0{width}d}'.format(width=2, number=y)
    col_names = [col for col in hist.columns if y in col[2:4] and len(col)==8]

    for z in range(n3):  # ethnicity
        z = '{number:0{width}d}'.format(width=2, number=z)
        col_names2 = [col for col in col_names if z in col[4:6]]

        col_two_or_more_races = []
        for x in range(n4):  # race
            if x >= 0 and x <= 5:
                x = '{number:0{width}d}'.format(width=2, number=x)
                col_names3 = [col for col in col_names2 if x in col[6:8]]
                hist[x + y + z] = hist[col_names3].sum(axis=1)
            else:
                x = '{number:0{width}d}'.format(width=2, number=x)
                col_names3 = [col for col in col_names2 if x in col[6:8]]
                col_two_or_more_races.extend(col_names3)
        hist['06' + y + z] = hist[col_two_or_more_races].sum(axis=1)

hist.drop([col for col in hist.columns if len(col)==8], axis=1, inplace=True)
hist

,TRACT,000000,010000,020000,030000,040000,050000,060000,000001,010001,...,040100,050100,060100,000101,010101,020101,030101,040101,050101,060101
0,39049000110,438,6,0,7,0,4,6,29,0,...,0,2,1,17,3,0,0,0,6,0
1,39049000120,467,4,0,11,0,2,6,13,0,...,1,0,3,18,0,0,0,0,4,0
2,39049000210,430,11,0,6,0,4,13,10,0,...,0,2,4,34,0,0,0,0,4,0
3,39049000220,653,3,1,12,0,6,13,20,0,...,0,6,4,16,0,2,0,0,8,1
4,39049000310,313,205,0,17,0,2,25,15,1,...,2,5,8,40,1,1,0,0,36,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,39049010500,1821,35,1,409,0,2,33,27,0,...,1,8,8,70,0,1,0,0,19,0
280,39049010601,1408,36,0,146,0,3,32,16,3,...,0,2,4,86,0,0,0,0,13,1
281,39049010602,1585,45,3,139,0,4,19,13,1,...,0,8,11,71,2,2,0,0,25,0
282,39049010700,83,11,0,4,0,0,2,6,1,...,1,2,2,10,0,0,0,0,14,0
283,39049980000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Disclosure risks before protection

In [3]:
import numpy as np

pd.set_option('use_inf_as_na', True)
a = hist.iloc[:,1:].apply(lambda x: 1 / x).to_numpy()
a[~np.isfinite(a)] = 0
print("Identification prob: ", np.sum(a) / a.size)

Identification prob:  0.1667384238525854

In [4]:
import numpy as np

u = hist.iloc[:,1:]
print("Unique prob: ", np.count_nonzero(u == 1) / u.size)

Unique prob:  0.08601609657947686

Model inputs

In [5]:
import numpy as np

# define all the input data for the model
I, K = hist.shape[0], hist.shape[1] - 1
nj = 20
r = 3
p = 0.2 * I * K

V = []
for k in range(1, K+1):
    V.append(hist.index[(hist.iloc[:,k] <= r) & (hist.iloc[:,k] > 0)].tolist())

count = 0
for listElem in V:
    count += len(listElem)  
print(count)

A = hist.iloc[:,1:].to_numpy()
print(A.shape, A[0])

W = hist.iloc[:,1:].apply(lambda x: 1 + 1 / x).to_numpy()
W = np.nan_to_num(W, posinf=10) 
print(W.shape, W[0])

1497
(284, 28) [ 438    6    0    7    0    4    6   29    0    1    0    0    1    1
 2733   31    1   29    0    2    1   17    3    0    0    0    6    0]
(284, 28) [ 1.00228311  1.16666667 10.          1.14285714 10.          1.25
  1.16666667  1.03448276 10.          2.         10.         10.
  2.          2.          1.0003659   1.03225806  2.          1.03448276
 10.          1.5         2.          1.05882353  1.33333333 10.
 10.         10.          1.16666667 10.        ]

Coverage I: all except the origin and other uniques

In [6]:
import numpy as np

## define coverage aijk
T = np.ones((I, I, K))

for i in range(I): 
    for j in range(I):
        for k in range(K):
            if i == j or j in V[k]:
                T[i, j, k] = 0
T

array([[[0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 0., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 0., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 1., 0., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 0., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.]]])

Coverage II: neighboring

In [87]:
import numpy as np
import geopandas as gpd
from pysal.lib import weights

filename_gdf = 'data/franklin_tract10.json'
gdf = gpd.read_file(filename_gdf)
gdf['GEOID10'] = gdf['GEOID10'].astype(str)
wr = weights.distance.KNN.from_dataframe(gdf, k=10)
print(wr.neighbors[0])

## define coverage aijk
T = np.zeros((I, I, K))
for i in wr.neighbors:
    neighbors_idx = wr.neighbors[i]
    for j in neighbors_idx:
        geoid = gdf.loc[[j],'GEOID10'].values[0]
        idx = hist.loc[hist["TRACT"] == geoid].index[0]
        for k in range(K):
            if j not in V[k]:
                T[i, j, k] = 1
T

[4, 90, 89, 276, 12, 123, 171, 1, 180, 13]

array([[[0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

Run model

In [7]:
import pandas as pd
from gurobipy import Model, GRB, LinExpr, quicksum

# initialize model
m = Model('td')
# m.Params.LogToConsole = 0

# add objective function
obj = LinExpr()

# add decision variables and objective function
theta = {}     ## decision vairable
for k in range(K):
    if len(V[k]) == 0:
        continue
    for i in V[k]:
        # m.update()
        # objective
        for j in range(I):
            theta[i, j, k] = m.addVar(vtype=GRB.CONTINUOUS, lb=0, ub=1, name="theta_%d_%d_%d"%(i, j, k))
            obj += T[i, j, k] * theta[i, j, k] * A[i, k]

m.setObjective(obj, GRB.MAXIMIZE)

# add constraints
for k in range(K):
    if len(V[k]) == 0:
        continue
    for i in V[k]:
        m.addConstr(quicksum(theta[i, j, k] for j in range(I)) <= 1)

m.addConstr(quicksum(quicksum(quicksum(W[j, k] * theta[i, j, k] * A[i, k] for i in V[k]) for k in range(K)) for j in range(I)) <= p)

for j in range(I):
    m.addConstr(quicksum(quicksum(theta[i, j, k] * A[i, k] for i in V[k]) for k in range(K)) <= nj)

m.update()
m.optimize()

Academic license - for non-commercial use only - expires 2022-08-05
Using license file C:\Users\10716\gurobi.lic
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 1782 rows, 425148 columns and 1275444 nonzeros
Model fingerprint: 0x737a3656
Coefficient statistics:
  Matrix range     [1e+00, 3e+01]
  Objective range  [1e+00, 3e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 2e+03]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 0 rows and 130441 columns
Presolve time: 1.20s
Presolved: 1782 rows, 294707 columns, 884121 nonzeros

Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 1.746e+04
 Factor NZ  : 2.704e+04 (roughly 7 MBytes of memory)
 Factor Ops : 2.354e+06 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   5.15774986e+05  2.67835252e+03  5.67e+04 4.85e-01  6.05e+00     2s
   1   7.72037415e+04  3.28121442e+03  8.26e+03 5.89e-01  9.17e-01     2s
   2   1.16977832e+04  3.11165467e+03  1.00e+03 0.00e+00  1.20e-01     2s
   3   5.26455784e+03  2.81173537e+03  2.91e+02 0.00e+00  3.62e-02     2s
   4   3.89384367e+03  2.66603736e+03  1.40e+02 0.00e+00  1.74e-02     2s
   5   3.51064743e+03  2.58001109e+03  1.01e+02 0.00e+00  1.27e-02     2s
   6   3.22103352e+03  2.30033790e+03  7.11e+01 0.00e+00  8.15e-03     2s
   7   3.16806676e+03  2.18573105e+03  6.55e+01 0.00e+00  7.00e-03     2s
   8   3.15148860e+03  1.99565179e+03  6.39e+01 0.00e+00  6.86e-03     2s
   9   3.12547702e+03  1.85341104e+03  6.21e+01 0.00e+00  6.69e-03     2s
  10   3.06955614e+03  1.76145987e+03  5.89e+01 0.00e+00  6.02e-03     2s
  11   3.05716466e+03  1.78535168e+03  5.84e+01 0.00e+00  5.94e-03     2s
  12   2.99855859e+03  1.98877139e+03  5.58e+01 0.00e+00  6.27e-03     2s
  13   2.93597272e+03  1.91101326e+03  5.33e+01 0.00e+00  6.16e-03     2s
  14   2.83464735e+03  1.82475339e+03  4.92e+01 7.11e-15  6.00e-03     2s
  15   2.72592035e+03  1.70946222e+03  4.49e+01 7.11e-15  5.24e-03     2s
  16   2.62756251e+03  1.71931332e+03  4.11e+01 7.11e-15  5.19e-03     2s
  17   2.54180600e+03  1.70651896e+03  3.78e+01 3.55e-15  5.08e-03     2s
  18   2.37309319e+03  1.69448263e+03  3.14e+01 3.55e-15  4.79e-03     2s
  19   2.22002285e+03  1.65826457e+03  2.57e+01 7.11e-15  4.06e-03     2s
  20   2.08379441e+03  1.64578212e+03  2.06e+01 7.11e-15  3.76e-03     2s
  21   2.07816843e+03  1.61956084e+03  2.04e+01 3.55e-15  3.29e-03     2s
  22   2.01497049e+03  1.59090506e+03  1.81e+01 3.55e-15  2.59e-03     2s
  23   1.93983363e+03  1.56879778e+03  1.53e+01 5.33e-15  1.94e-03     2s
  24   1.81710036e+03  1.56099066e+03  1.08e+01 5.33e-15  1.55e-03     2s
  25   1.77805470e+03  1.55072921e+03  9.33e+00 7.11e-15  1.22e-03     2s
  26   1.72729770e+03  1.54646631e+03  7.46e+00 7.11e-15  1.02e-03     2s
  27   1.70120160e+03  1.53840907e+03  6.49e+00 5.33e-15  7.43e-04     2s
  28   1.65972675e+03  1.53680488e+03  4.96e+00 3.55e-15  5.97e-04     2s
  29   1.65090057e+03  1.53364739e+03  4.63e+00 7.11e-15  5.05e-04     2s
  30   1.64326441e+03  1.53260396e+03  4.34e+00 7.11e-15  4.67e-04     2s
  31   1.63601139e+03  1.53221806e+03  4.07e+00 7.11e-15  4.38e-04     2s
  32   1.61087613e+03  1.53101260e+03  3.13e+00 1.78e-15  3.35e-04     2s
  33   1.60349823e+03  1.52984190e+03  2.86e+00 3.55e-15  2.87e-04     2s
  34   1.57119902e+03  1.52946061e+03  1.66e+00 3.55e-15  1.95e-04     2s
  35   1.56223334e+03  1.52861733e+03  1.33e+00 2.28e-15  1.58e-04     2s
  36   1.54796654e+03  1.52757940e+03  7.99e-01 7.11e-15  8.90e-05     2s
  37   1.54191757e+03  1.52716108e+03  5.75e-01 7.11e-15  6.16e-05     2s
  38   1.53877486e+03  1.52690868e+03  4.59e-01 7.11e-15  4.72e-05     2s
  39   1.53069278e+03  1.52672632e+03  1.58e-01 3.55e-15  2.00e-05     2s
  40   1.52870110e+03  1.52660561e+03  8.45e-02 3.55e-15  1.17e-05     2s
  41   1.52654347e+03  1.52654856e+03  1.62e-03 3.55e-15  1.54e-06     2s
  42   1.52652582e+03  1.52654142e+03  8.21e-04 3.55e-15  1.16e-06     2s
  43   1.52651467e+03  1.52651470e+03  2.15e-04 7.11e-15  1.85e-07     2s
  44   1.52651425e+03  1.52651357e+03  1.66e-04 3.55e-15  1.22e-07     2s
  45   1.52651215e+03  1.52651175e+03  8.99e-05 7.11e-15  6.55e-08     2s
  46   1.52651121e+03  1.52651142e+03  2.78e-06 7.11e-15  8.43e-09     2s
  47   1.52651121e+03  1.52651157e+03  2.62e-07 7.11e-15  1.08e-08     2s
  48   1.52651124e+03  1.52651140e+03  0.00e+00 2.84e-14  4.60e-09     2s
  49   1.52651140e+03  1.52651140e+03  3.75e-13 1.42e-14  1.34e-12     2s

Barrier solved model in 49 iterations and 2.17 seconds
Optimal objective 1.52651140e+03

Crossover log...

      28 DPushes remaining with DInf 0.0000000e+00                 2s
       0 DPushes remaining with DInf 0.0000000e+00                 2s

     174 PPushes remaining with PInf 0.0000000e+00                 2s
       0 PPushes remaining with PInf 0.0000000e+00                 2s

  Push phase complete: Pinf 0.0000000e+00, Dinf 3.9010462e-14      2s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
     205    1.5265114e+03   0.000000e+00   0.000000e+00      2s

Use crossover to convert LP symmetric solution to basic solution...
Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 2s

    2099 PPushes remaining with PInf 0.0000000e+00                 2s

Solved with dual simplex
Solved in 3117 iterations and 2.45 seconds
Optimal objective  1.526511402e+03

In [ ]:
for var in m.getVars():
    print(var.VarName, var.X)

Disclosure risks after protection

In [11]:
theta_all = np.empty([I, I, K])
for k in range(K):
    for i in range(I):
        if i not in V[k] and A[i, k] != 0:
            theta_all[i, i, k] = 1

for var in m.getVars():
    name = var.VarName.split("_")
    theta_all[int(name[1]), int(name[2]), int(name[3])] = var.X

# check
np.sum(theta_all, axis=1)

array([[1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
p = np.ones([I, K])
b = hist.iloc[:,1:].to_numpy()
for k in range(K):
    for i in range(I):
        sum = 0
        for j in range(I):
            if i != j:
                sum += theta_all[j, i, k] * b[j, k]
        p[i, k] = theta_all[i, i, k] / (theta_all[i, i, k] * b[i, k] + sum)
p[~np.isfinite(p)] = 0
print("Identification prob: ", np.sum(p) / p.size)

C:\Users\10716\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':

Identification prob:  0.036474727890425475

In [13]:
v = 0
for k in range(K):
    for i in range(I):
        if b[i, k] == 1 and theta_all[i, i, k] == 1:
            v += 1

print("Unique prob: ", np.sum(v) / (I * K))

Unique prob:  0.0